---
apiVersion: v1
kind: Service
metadata:
  name: green-svc
spec:
    type: NodePort
    selector:
       color: green
       version: v2
    ports:
       - port: 80
         targetPort: 8080
         nodePort: 31786
...
