---
apiVersion: v1
kind: Service
metadata:
       name: live-svc
spec:
    type: LoadBalancer
    selector:
        color: blue
    ports:
      - port: 80
        targetPort: 8080
        nodePort: 31785
...
